### ISSUE TITLE
add support for sonarqube to the library + jenkinsfiles

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-pipeline-library#12]
it'd be awesome if we automatically invoked sonarqube builds whenever its running in a developer namespace

**Comment by iocanel** [comment]
Our sonarqube stuff are not in the best shape atm. Started: https://github.com/fabric8io/fabric8-devops/issues/690

**Comment by rajdavies** [comment]
currently being held up by this: https://issues.jenkins-ci.org/browse/JENKINS-33510

**Comment by rajdavies** [comment]
fixed by https://github.com/fabric8io/fabric8-pipeline-library/pull/95
