### ISSUE TITLE
can you guys provide operation with mvn install -DskipTests 

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/fabric8-pipeline-library#18]
can you guys provide operation with mvn install -DskipTests

**Comment by ilterpehlivan** [comment]
Hi Robin,

I fixed this issue by creating my own custom pipeline and add it into Jenkins.
Here is the steps:

1- Clone the fabric8-pipeline-library to your local
2- Make change in the "mavenCanaryRelease.groovy" I added following lines:
   def flow = new io.fabric8.Fabric8Commands()
	def skipTests = config.skipTests ? config.skipTests : false
   sh "mvn clean -e -U deploy -Dmaven.test.skip=${skipTests}"
3- Checking the pipeline into your local gogs repo
4- Add it into Jenkins as custom library (Check global pipeline library documentation in Jenkins)
5- Change your Jenkinsfile as:
@Library('custom-pipeline-library')
6- Add skipTest parameter to mavenRelease pipeline:
stage 'Build Release'
    mavenCanaryRelease {
      version = canaryVersion
	  skipTests = true
    }

I hope that helps

**Comment by rajdavies** [comment]
Fixed by https://github.com/fabric8io/fabric8-pipeline-library/pull/114
