### ISSUE TITLE
Approve step outside of a mavenNode{...} definition doesn't terminate build pod

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-pipeline-library#204]
Testing Using a Jenkinsfile of:
```
#!/usr/bin/groovy
@Library('github.com/fabric8io/fabric8-pipeline-library@master')
def dummy
mavenNode{
  container('maven'){
    echo 'inside build pod'
  }
}
node{
    approve {
      room = null
      version = '1.0.0'
      console = null
      environment = 'Stage'
    }
}
```
The build pod is kepy running until the jobs has finished rather than at the closing parenthesis of the `mavenNode`, this means that build pods will stick around during the approve step which is a waste of resources.

@iocanel suggested trying this https://github.com/fabric8io/kubernetes-plugin/commit/2b4f6d80016eb7f17b945b32dfd73c023914da9e which works great. I wonder however if instead we need to mark the build pod as complete list the openshift s2i build pods?

**Comment by jstrachan** [comment]
@rawlingsj this now fixed?

**Comment by rawlingsj** [comment]
yep it's fixed
