### ISSUE TITLE
we should throw an error if swizzle image name doesn't replace anything

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-pipeline-library#270]
to get faster feedback and avoid deploying an invalid image we ought to error if we don't change anything here https://github.com/fabric8io/fabric8-pipeline-library/blob/master/src/io/fabric8/Fabric8Commands.groovy#L16

**Comment by hectorj2f** [comment]
+1 on this

**Comment by rawlingsj** [comment]
forgot the magic text to auto close.  fix is merged
