### ISSUE TITLE
maven fails to deploy application changes

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-pipeline-library#391]
In the context of [openshift.io application deployment](https://github.com/openshiftio/openshift.io/issues/2505#issuecomment-371732158) an important [issue (#1226)](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/CHANGELOG.md) has been fixed in the recent release (3.5.38) of fabric8 maven plugin (FMP).

Existing or new builds should use FMP 3.5.38 through patching the pipeline

**Comment by chmouel** [comment]
LGTM
