### ISSUE TITLE
Exception: "Scripts not permitted to use new io.fabric8.openshift.client.DefaultOpenShiftClient"

### ISSUE THREAD

**Issue by qabbasi** [fabric8io/fabric8-pipeline-library#46]
Aloha,

currently the Fabric8-Jenkins-Build-Job runs into an weird exception when creating a new project using v2.2.192.

I suppose it's in some fashion (or not) related with the following line but I'm not sure: https://github.com/fabric8io/fabric8-pipeline-library/blob/d49b65c34feb3b33fabcb562158a16f90da6d424/src/io/fabric8/Fabric8Commands.groovy#L554

The original stack trace can be found here:
https://gist.github.com/anonymous/8b6b08236331677d24e42ff62edf571b

Thanks for any hint,
Qaiser

**Comment by r4j4h** [comment]
A temporary workaround is to go to Manage Jenkins -> In-process Script Approval and manually Approve the entries.

**Comment by qabbasi** [comment]
Tks, I'll check it out
